# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for JobHunt.

Bundles Python + Qt + QtWebEngine + the full jobhunt package into a
distributable folder (one-folder mode — required for QtWebEngine; the
"one-file" mode is unreliable with Chromium's data files).

Build with:
    pyinstaller jobhunt.spec --clean --noconfirm

Output:
    dist/JobHunt/JobHunt.exe   ← the launcher
    dist/JobHunt/_internal/    ← Python runtime, Qt, Chromium, our package

The Inno Setup installer (installer/JobHunt.iss) wraps the whole dist/JobHunt
folder into a one-click .exe installer that drops everything under Program
Files and creates the Start Menu shortcut.
"""

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# ---------------------------------------------------------------------------
# Data files we ship next to the .exe
# ---------------------------------------------------------------------------

datas = []

# QtWebEngine ships Chromium binaries + Pak resources + locales. PyInstaller's
# PySide6 hook covers most of it, but explicit `collect_data_files` for the
# WebEngine submodule guarantees the locale tables come along.
datas += collect_data_files(
    "PySide6.QtWebEngineCore", include_py_files=False,
)
datas += collect_data_files(
    "PySide6.QtWebEngineWidgets", include_py_files=False,
)

# Our embedded logo lives at jobhunt/assets/_logo_data.py and is imported as a
# regular Python module — no data-file copy needed for it. But the assets
# README is informational, harmless to include:
datas += [("jobhunt/assets/README.md", "jobhunt/assets")]


# ---------------------------------------------------------------------------
# Hidden imports — modules pulled in dynamically (string imports, late binds)
# ---------------------------------------------------------------------------

hiddenimports = []

# `anthropic` and `openai` lazy-import their HTTP transports.
hiddenimports += collect_submodules("anthropic")
hiddenimports += collect_submodules("openai")

# pdfplumber pulls in pdfminer.six dynamically, and reportlab loads font
# backends on demand.
hiddenimports += collect_submodules("pdfplumber")
hiddenimports += collect_submodules("reportlab")

# docx (python-docx) has lazy XML imports.
hiddenimports += collect_submodules("docx")


# ---------------------------------------------------------------------------
# Analysis — entry point + dependency resolution
# ---------------------------------------------------------------------------

block_cipher = None

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Test / dev frameworks we ship deps via — PyInstaller would happily
        # pull in entire test stacks unless we say no.
        "pytest", "_pytest", "pluggy", "iniconfig",
        # Tcl/Tk not used; Qt provides our UI.
        "tkinter",
        # Build tooling itself
        "pyinstaller",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="JobHunt",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                 # UPX compression often trips Defender; skip.
    console=False,             # GUI app — no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="installer/JobHunt.ico",   # generated by build.py from the embedded PNG
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="JobHunt",
)
